[book]
title = "Atomic Habits: Tiny Changes, Remarkable Results"
authors = ["Rishabh"]
description = ""
language = "en"
multilingual = false
src = "src"

[build]
create-missing = false

[rust]
edition = "2018"

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/constorion/atomic-habits"
git-repository-icon = "fa-github"
mathjax-support = true